// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="combination_lock_combination_lock,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.301286,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4,HLS_SYN_LUT=208,HLS_VERSION=2025_1}" *)

module combination_lock (
        ap_clk,
        ap_rst,
        x,
        enter,
        lock,
        door_open,
        seven_segment_data,
        seven_segment_enable
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [3:0] x;
input  [0:0] enter;
input  [0:0] lock;
output  [0:0] door_open;
output  [7:0] seven_segment_data;
output  [3:0] seven_segment_enable;

reg   [2:0] state;
wire   [2:0] next_state_4_fu_340_p21;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] door_open_local_2_fu_396_p9;
wire   [7:0] ref_tmp_0_0_0_s_fu_423_p13;
wire   [0:0] next_state_1_fu_182_p2;
wire   [0:0] icmp_ln111_fu_192_p2;
wire   [0:0] next_state_2_fu_206_p2;
wire   [0:0] door_open_local_1_fu_220_p2;
wire   [0:0] icmp_ln69_1_fu_240_p2;
wire   [0:0] icmp_ln69_2_fu_252_p2;
wire   [0:0] icmp_ln69_3_fu_264_p2;
wire   [0:0] icmp_ln69_4_fu_276_p2;
wire   [0:0] xor_ln42_fu_288_p2;
wire   [0:0] icmp_ln69_fu_234_p2;
wire   [0:0] and_ln42_fu_246_p2;
wire   [0:0] and_ln42_1_fu_258_p2;
wire   [0:0] and_ln42_2_fu_270_p2;
wire   [0:0] and_ln42_3_fu_282_p2;
wire   [0:0] and_ln42_4_fu_294_p2;
wire   [0:0] and_ln42_5_fu_300_p2;
wire   [0:0] and_ln42_6_fu_306_p2;
wire   [0:0] and_ln42_7_fu_312_p2;
wire   [2:0] next_state_4_fu_340_p2;
wire   [2:0] next_state_4_fu_340_p4;
wire   [2:0] next_state_4_fu_340_p6;
wire   [2:0] next_state_4_fu_340_p8;
wire   [2:0] next_state_4_fu_340_p10;
wire   [2:0] next_state_4_fu_340_p19;
wire   [8:0] next_state_4_fu_340_p20;
wire   [8:0] sel_tmp_fu_318_p10;
wire   [0:0] door_open_local_2_fu_396_p2;
wire   [0:0] door_open_local_2_fu_396_p7;
wire   [1:0] door_open_local_2_fu_396_p8;
wire   [31:0] ref_tmp_0_0_0_s_fu_423_p12;
reg   [0:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire  signed [8:0] next_state_4_fu_340_p1;
wire   [8:0] next_state_4_fu_340_p3;
wire   [8:0] next_state_4_fu_340_p5;
wire   [8:0] next_state_4_fu_340_p7;
wire   [8:0] next_state_4_fu_340_p9;
wire   [8:0] next_state_4_fu_340_p11;
wire   [8:0] next_state_4_fu_340_p13;
wire   [8:0] next_state_4_fu_340_p15;
wire   [8:0] next_state_4_fu_340_p17;
wire  signed [1:0] door_open_local_2_fu_396_p1;
wire   [1:0] door_open_local_2_fu_396_p3;
wire   [1:0] door_open_local_2_fu_396_p5;
wire   [31:0] ref_tmp_0_0_0_s_fu_423_p1;
wire   [31:0] ref_tmp_0_0_0_s_fu_423_p3;
wire   [31:0] ref_tmp_0_0_0_s_fu_423_p5;
wire   [31:0] ref_tmp_0_0_0_s_fu_423_p7;
wire   [31:0] ref_tmp_0_0_0_s_fu_423_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 state = 3'd0;
#0 ap_CS_fsm = 1'd1;
end

(* dissolve_hierarchy = "yes" *) combination_lock_sparsemux_19_9_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 9'h100 ),
    .din0_WIDTH( 3 ),
    .CASE1( 9'h80 ),
    .din1_WIDTH( 3 ),
    .CASE2( 9'h40 ),
    .din2_WIDTH( 3 ),
    .CASE3( 9'h20 ),
    .din3_WIDTH( 3 ),
    .CASE4( 9'h10 ),
    .din4_WIDTH( 3 ),
    .CASE5( 9'h8 ),
    .din5_WIDTH( 3 ),
    .CASE6( 9'h4 ),
    .din6_WIDTH( 3 ),
    .CASE7( 9'h2 ),
    .din7_WIDTH( 3 ),
    .CASE8( 9'h1 ),
    .din8_WIDTH( 3 ),
    .def_WIDTH( 3 ),
    .sel_WIDTH( 9 ),
    .dout_WIDTH( 3 ))
sparsemux_19_9_3_1_1_U1(
    .din0(next_state_4_fu_340_p2),
    .din1(next_state_4_fu_340_p4),
    .din2(next_state_4_fu_340_p6),
    .din3(next_state_4_fu_340_p8),
    .din4(next_state_4_fu_340_p10),
    .din5(3'd0),
    .din6(3'd1),
    .din7(3'd2),
    .din8(3'd3),
    .def(next_state_4_fu_340_p19),
    .sel(next_state_4_fu_340_p20),
    .dout(next_state_4_fu_340_p21)
);

(* dissolve_hierarchy = "yes" *) combination_lock_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U2(
    .din0(door_open_local_2_fu_396_p2),
    .din1(door_open_local_1_fu_220_p2),
    .din2(1'd0),
    .def(door_open_local_2_fu_396_p7),
    .sel(door_open_local_2_fu_396_p8),
    .dout(door_open_local_2_fu_396_p9)
);

(* dissolve_hierarchy = "yes" *) combination_lock_sparsemux_11_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 32'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 32'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 32'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 32'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 32'h4 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 32 ),
    .dout_WIDTH( 8 ))
sparsemux_11_32_8_1_1_U3(
    .din0(8'd192),
    .din1(8'd249),
    .din2(8'd164),
    .din3(8'd176),
    .din4(8'd153),
    .def(8'd192),
    .sel(ref_tmp_0_0_0_s_fu_423_p12),
    .dout(ref_tmp_0_0_0_s_fu_423_p13)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        state <= next_state_4_fu_340_p21;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln42_1_fu_258_p2 = (icmp_ln69_2_fu_252_p2 & enter);

assign and_ln42_2_fu_270_p2 = (icmp_ln69_3_fu_264_p2 & enter);

assign and_ln42_3_fu_282_p2 = (icmp_ln69_4_fu_276_p2 & enter);

assign and_ln42_4_fu_294_p2 = (xor_ln42_fu_288_p2 & icmp_ln69_4_fu_276_p2);

assign and_ln42_5_fu_300_p2 = (xor_ln42_fu_288_p2 & icmp_ln69_3_fu_264_p2);

assign and_ln42_6_fu_306_p2 = (xor_ln42_fu_288_p2 & icmp_ln69_2_fu_252_p2);

assign and_ln42_7_fu_312_p2 = (xor_ln42_fu_288_p2 & icmp_ln69_1_fu_240_p2);

assign and_ln42_fu_246_p2 = (icmp_ln69_1_fu_240_p2 & enter);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign door_open = door_open_local_2_fu_396_p9;

assign door_open_local_1_fu_220_p2 = ((x == 4'd6) ? 1'b1 : 1'b0);

assign door_open_local_2_fu_396_p2 = (lock ^ 1'd1);

assign door_open_local_2_fu_396_p7 = 'bx;

assign door_open_local_2_fu_396_p8 = {{icmp_ln69_fu_234_p2}, {and_ln42_fu_246_p2}};

assign icmp_ln111_fu_192_p2 = ((x == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln69_1_fu_240_p2 = ((state == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln69_2_fu_252_p2 = ((state == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln69_3_fu_264_p2 = ((state == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln69_4_fu_276_p2 = ((state == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_234_p2 = ((state == 3'd4) ? 1'b1 : 1'b0);

assign next_state_1_fu_182_p2 = ((x == 4'd2) ? 1'b1 : 1'b0);

assign next_state_2_fu_206_p2 = ((x == 4'd4) ? 1'b1 : 1'b0);

assign next_state_4_fu_340_p10 = next_state_1_fu_182_p2;

assign next_state_4_fu_340_p19 = 'bx;

assign next_state_4_fu_340_p2 = ((lock[0:0] == 1'b1) ? 3'd0 : 3'd4);

assign next_state_4_fu_340_p20 = {{{{{{{{{icmp_ln69_fu_234_p2}, {and_ln42_fu_246_p2}}, {and_ln42_1_fu_258_p2}}, {and_ln42_2_fu_270_p2}}, {and_ln42_3_fu_282_p2}}, {and_ln42_4_fu_294_p2}}, {and_ln42_5_fu_300_p2}}, {and_ln42_6_fu_306_p2}}, {and_ln42_7_fu_312_p2}};

assign next_state_4_fu_340_p4 = ((door_open_local_1_fu_220_p2[0:0] == 1'b1) ? 3'd4 : 3'd0);

assign next_state_4_fu_340_p6 = ((next_state_2_fu_206_p2[0:0] == 1'b1) ? 3'd3 : 3'd0);

assign next_state_4_fu_340_p8 = ((icmp_ln111_fu_192_p2[0:0] == 1'b1) ? 3'd2 : 3'd0);

assign ref_tmp_0_0_0_s_fu_423_p12 = next_state_4_fu_340_p21;

assign sel_tmp_fu_318_p10 = {{{{{{{{{icmp_ln69_fu_234_p2}, {and_ln42_fu_246_p2}}, {and_ln42_1_fu_258_p2}}, {and_ln42_2_fu_270_p2}}, {and_ln42_3_fu_282_p2}}, {and_ln42_4_fu_294_p2}}, {and_ln42_5_fu_300_p2}}, {and_ln42_6_fu_306_p2}}, {and_ln42_7_fu_312_p2}};

assign seven_segment_data = ref_tmp_0_0_0_s_fu_423_p13;

assign seven_segment_enable = 4'd14;

assign xor_ln42_fu_288_p2 = (enter ^ 1'd1);

endmodule //combination_lock
