# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/parallel_sys.xdc

# Block Designs: bd/paralle_serial_sys/paralle_serial_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==paralle_serial_sys || ORIG_REF_NAME==paralle_serial_sys} -quiet] -quiet

# IP: bd/paralle_serial_sys/ip/paralle_serial_sys_serial2parallel_0_0/paralle_serial_sys_serial2parallel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==paralle_serial_sys_serial2parallel_0_0 || ORIG_REF_NAME==paralle_serial_sys_serial2parallel_0_0} -quiet] -quiet

# IP: bd/paralle_serial_sys/ip/paralle_serial_sys_parallel2serial_0_0/paralle_serial_sys_parallel2serial_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==paralle_serial_sys_parallel2serial_0_0 || ORIG_REF_NAME==paralle_serial_sys_parallel2serial_0_0} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/Parallel_Serial_Sys_Vivado/Parallel_Serial_Sys_Vivado.gen/sources_1/bd/paralle_serial_sys/paralle_serial_sys_ooc.xdc
