# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lenovo/Simulation_Linux/HLS/LED_Controller_Vivado/LED_Controller_Vivado.srcs/sources_1/bd/LED_Controller/ip/LED_Controller_led_ON_0_0/LED_Controller_led_ON_0_0.xci
# IP: The module: 'LED_Controller_led_ON_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/LED_Controller_Vivado/LED_Controller_Vivado.gen/sources_1/bd/LED_Controller/ip/LED_Controller_led_ON_0_0/constraints/led_ON_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED_Controller_led_ON_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lenovo/Simulation_Linux/HLS/LED_Controller_Vivado/LED_Controller_Vivado.srcs/sources_1/bd/LED_Controller/ip/LED_Controller_led_ON_0_0/LED_Controller_led_ON_0_0.xci
# IP: The module: 'LED_Controller_led_ON_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/LED_Controller_Vivado/LED_Controller_Vivado.gen/sources_1/bd/LED_Controller/ip/LED_Controller_led_ON_0_0/constraints/led_ON_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED_Controller_led_ON_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
