-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity leading_one is
port (
    a : IN STD_LOGIC_VECTOR (8 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (4 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of leading_one is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "leading_one_leading_one,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.694571,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=77,HLS_VERSION=2025_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal trunc_ln41_fu_156_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_92_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_100_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln17_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_108_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln23_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_116_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln23_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_124_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln29_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_132_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln29_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln32_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_140_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln32_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln35_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln20_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln23_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln29_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln32_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln38_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_8_fu_314_p18 : STD_LOGIC_VECTOR (4 downto 0);
    signal retval_8_fu_314_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal retval_8_fu_314_p20 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal retval_8_fu_314_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p13 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p15 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_8_fu_314_p17 : STD_LOGIC_VECTOR (7 downto 0);

    component leading_one_sparsemux_19_8_5_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (7 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (7 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (7 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (7 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (7 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (7 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (7 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (7 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (7 downto 0);
        din8_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        din3 : IN STD_LOGIC_VECTOR (4 downto 0);
        din4 : IN STD_LOGIC_VECTOR (4 downto 0);
        din5 : IN STD_LOGIC_VECTOR (4 downto 0);
        din6 : IN STD_LOGIC_VECTOR (4 downto 0);
        din7 : IN STD_LOGIC_VECTOR (4 downto 0);
        din8 : IN STD_LOGIC_VECTOR (4 downto 0);
        def : IN STD_LOGIC_VECTOR (4 downto 0);
        sel : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    sparsemux_19_8_5_1_1_U1 : component leading_one_sparsemux_19_8_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10000000",
        din0_WIDTH => 5,
        CASE1 => "01000000",
        din1_WIDTH => 5,
        CASE2 => "00100000",
        din2_WIDTH => 5,
        CASE3 => "00010000",
        din3_WIDTH => 5,
        CASE4 => "00001000",
        din4_WIDTH => 5,
        CASE5 => "00000100",
        din5_WIDTH => 5,
        CASE6 => "00000010",
        din6_WIDTH => 5,
        CASE7 => "00000001",
        din7_WIDTH => 5,
        CASE8 => "00000000",
        din8_WIDTH => 5,
        def_WIDTH => 5,
        sel_WIDTH => 8,
        dout_WIDTH => 5)
    port map (
        din0 => ap_const_lv5_8,
        din1 => ap_const_lv5_7,
        din2 => ap_const_lv5_6,
        din3 => ap_const_lv5_5,
        din4 => ap_const_lv5_4,
        din5 => ap_const_lv5_3,
        din6 => ap_const_lv5_2,
        din7 => ap_const_lv5_1,
        din8 => retval_8_fu_314_p18,
        def => retval_8_fu_314_p19,
        sel => retval_8_fu_314_p20,
        dout => retval_8_fu_314_p21);




    and_ln20_fu_180_p2 <= (xor_ln17_fu_174_p2 and tmp_1_fu_100_p3);
    and_ln23_fu_198_p2 <= (xor_ln20_fu_192_p2 and tmp_2_fu_108_p3);
    and_ln26_fu_216_p2 <= (xor_ln23_fu_210_p2 and tmp_3_fu_116_p3);
    and_ln29_fu_234_p2 <= (xor_ln26_fu_228_p2 and tmp_4_fu_124_p3);
    and_ln32_fu_252_p2 <= (xor_ln29_fu_246_p2 and tmp_5_fu_132_p3);
    and_ln35_fu_270_p2 <= (xor_ln32_fu_264_p2 and tmp_6_fu_140_p3);
    and_ln38_fu_288_p2 <= (xor_ln35_fu_282_p2 and tmp_7_fu_148_p3);
    ap_return <= retval_8_fu_314_p21;
    index_fu_160_p2 <= (trunc_ln41_fu_156_p1 xor ap_const_lv1_1);
    or_ln20_fu_186_p2 <= (tmp_fu_92_p3 or tmp_1_fu_100_p3);
    or_ln23_fu_204_p2 <= (tmp_2_fu_108_p3 or or_ln20_fu_186_p2);
    or_ln26_fu_222_p2 <= (tmp_3_fu_116_p3 or or_ln23_fu_204_p2);
    or_ln29_fu_240_p2 <= (tmp_4_fu_124_p3 or or_ln26_fu_222_p2);
    or_ln32_fu_258_p2 <= (tmp_5_fu_132_p3 or or_ln29_fu_240_p2);
    or_ln35_fu_276_p2 <= (tmp_6_fu_140_p3 or or_ln32_fu_258_p2);
    retval_8_fu_314_p18 <= 
        ap_const_lv5_1F when (index_fu_160_p2(0) = '1') else 
        ap_const_lv5_0;
    retval_8_fu_314_p19 <= "XXXXX";
    retval_8_fu_314_p20 <= (((((((tmp_fu_92_p3 & and_ln20_fu_180_p2) & and_ln23_fu_198_p2) & and_ln26_fu_216_p2) & and_ln29_fu_234_p2) & and_ln32_fu_252_p2) & and_ln35_fu_270_p2) & and_ln38_fu_288_p2);
    tmp_1_fu_100_p3 <= a(7 downto 7);
    tmp_2_fu_108_p3 <= a(6 downto 6);
    tmp_3_fu_116_p3 <= a(5 downto 5);
    tmp_4_fu_124_p3 <= a(4 downto 4);
    tmp_5_fu_132_p3 <= a(3 downto 3);
    tmp_6_fu_140_p3 <= a(2 downto 2);
    tmp_7_fu_148_p3 <= a(1 downto 1);
    tmp_fu_92_p3 <= a(8 downto 8);
    trunc_ln41_fu_156_p1 <= a(1 - 1 downto 0);
    xor_ln17_fu_174_p2 <= (tmp_fu_92_p3 xor ap_const_lv1_1);
    xor_ln20_fu_192_p2 <= (or_ln20_fu_186_p2 xor ap_const_lv1_1);
    xor_ln23_fu_210_p2 <= (or_ln23_fu_204_p2 xor ap_const_lv1_1);
    xor_ln26_fu_228_p2 <= (or_ln26_fu_222_p2 xor ap_const_lv1_1);
    xor_ln29_fu_246_p2 <= (or_ln29_fu_240_p2 xor ap_const_lv1_1);
    xor_ln32_fu_264_p2 <= (or_ln32_fu_258_p2 xor ap_const_lv1_1);
    xor_ln35_fu_282_p2 <= (or_ln35_fu_276_p2 xor ap_const_lv1_1);
end behav;
