# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lenovo/Simulation_Linux/HLS/Leading_One_Vivado/Leading_One_Vivado.srcs/sources_1/bd/leading_one/ip/leading_one_leading_one_0_0/leading_one_leading_one_0_0.xci
# IP: The module: 'leading_one_leading_one_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Leading_One_Vivado/Leading_One_Vivado.gen/sources_1/bd/leading_one/ip/leading_one_leading_one_0_0/constraints/leading_one_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'leading_one_leading_one_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lenovo/Simulation_Linux/HLS/Leading_One_Vivado/Leading_One_Vivado.srcs/sources_1/bd/leading_one/ip/leading_one_leading_one_0_0/leading_one_leading_one_0_0.xci
# IP: The module: 'leading_one_leading_one_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Leading_One_Vivado/Leading_One_Vivado.gen/sources_1/bd/leading_one/ip/leading_one_leading_one_0_0/constraints/leading_one_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'leading_one_leading_one_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
