# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/comb_lock.xdc

# Block Designs: bd/comb_lock/comb_lock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comb_lock || ORIG_REF_NAME==comb_lock} -quiet] -quiet

# IP: bd/comb_lock/ip/comb_lock_combination_lock_0_0/comb_lock_combination_lock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comb_lock_combination_lock_0_0 || ORIG_REF_NAME==comb_lock_combination_lock_0_0} -quiet] -quiet

# IP: bd/comb_lock/ip/comb_lock_debouncer_0_0/comb_lock_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comb_lock_debouncer_0_0 || ORIG_REF_NAME==comb_lock_debouncer_0_0} -quiet] -quiet

# IP: bd/comb_lock/ip/comb_lock_debouncer_1_0/comb_lock_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comb_lock_debouncer_1_0 || ORIG_REF_NAME==comb_lock_debouncer_1_0} -quiet] -quiet

# IP: bd/comb_lock/ip/comb_lock_pulse_generator_0_0/comb_lock_pulse_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comb_lock_pulse_generator_0_0 || ORIG_REF_NAME==comb_lock_pulse_generator_0_0} -quiet] -quiet

# IP: bd/comb_lock/ip/comb_lock_pulse_generator_1_1/comb_lock_pulse_generator_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comb_lock_pulse_generator_1_1 || ORIG_REF_NAME==comb_lock_pulse_generator_1_1} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/Comb_Lock_Vivado/Comb_Lock_Vivado.gen/sources_1/bd/comb_lock/comb_lock_ooc.xdc
