# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3.xdc

# Block Designs: bd/LED_controller/LED_controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_controller || ORIG_REF_NAME==LED_controller} -quiet] -quiet

# IP: bd/LED_controller/ip/LED_controller_basic_output_0_0/LED_controller_basic_output_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_controller_basic_output_0_0 || ORIG_REF_NAME==LED_controller_basic_output_0_0} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/LED_test/LED_test.gen/sources_1/bd/LED_controller/LED_controller_ooc.xdc
