## Switches
set_property PACKAGE_PIN V17 [get_ports {slide_switches[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[0]}]
set_property PACKAGE_PIN V16 [get_ports {slide_switches[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[1]}]
set_property PACKAGE_PIN W16 [get_ports {slide_switches[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[2]}]
set_property PACKAGE_PIN W17 [get_ports {slide_switches[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[3]}]
set_property PACKAGE_PIN W15 [get_ports {slide_switches[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[4]}]
set_property PACKAGE_PIN V15 [get_ports {slide_switches[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[5]}]
set_property PACKAGE_PIN W14 [get_ports {slide_switches[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[6]}]
set_property PACKAGE_PIN W13 [get_ports {slide_switches[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[7]}]
set_property PACKAGE_PIN V2 [get_ports {slide_switches[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[8]}]
set_property PACKAGE_PIN T3 [get_ports {slide_switches[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[9]}]
set_property PACKAGE_PIN T2 [get_ports {slide_switches[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[10]}]
set_property PACKAGE_PIN R3 [get_ports {slide_switches[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[11]}]
set_property PACKAGE_PIN W2 [get_ports {slide_switches[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[12]}]
set_property PACKAGE_PIN U1 [get_ports {slide_switches[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[13]}]
set_property PACKAGE_PIN T1 [get_ports {slide_switches[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[14]}]
set_property PACKAGE_PIN R2 [get_ports {slide_switches[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {slide_switches[15]}]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property PACKAGE_PIN V3 [get_ports {leds[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property PACKAGE_PIN W3 [get_ports {leds[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property PACKAGE_PIN U3 [get_ports {leds[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property PACKAGE_PIN P3 [get_ports {leds[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
set_property PACKAGE_PIN N3 [get_ports {leds[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
set_property PACKAGE_PIN P1 [get_ports {leds[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
set_property PACKAGE_PIN L1 [get_ports {leds[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]


##7 segment display
set_property PACKAGE_PIN W7 [get_ports {sg_data[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[0]}]
set_property PACKAGE_PIN W6 [get_ports {sg_data[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[1]}]
set_property PACKAGE_PIN U8 [get_ports {sg_data[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[2]}]
set_property PACKAGE_PIN V8 [get_ports {sg_data[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[3]}]
set_property PACKAGE_PIN U5 [get_ports {sg_data[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[4]}]
set_property PACKAGE_PIN V5 [get_ports {sg_data[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[5]}]
set_property PACKAGE_PIN U7 [get_ports {sg_data[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[6]}]

set_property PACKAGE_PIN V7 [get_ports {sg_data[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_data[7]}]

set_property PACKAGE_PIN U2 [get_ports {sg_enable[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_enable[0]}]
set_property PACKAGE_PIN U4 [get_ports {sg_enable[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_enable[1]}]
set_property PACKAGE_PIN V4 [get_ports {sg_enable[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_enable[2]}]
set_property PACKAGE_PIN W4 [get_ports {sg_enable[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sg_enable[3]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports push_buttons[4]]
	set_property IOSTANDARD LVCMOS33 [get_ports push_buttons[4]]
set_property PACKAGE_PIN T18 [get_ports push_buttons[2]]
	set_property IOSTANDARD LVCMOS33 [get_ports push_buttons[2]]
set_property PACKAGE_PIN W19 [get_ports push_buttons[0]]
	set_property IOSTANDARD LVCMOS33 [get_ports push_buttons[0]]
set_property PACKAGE_PIN T17 [get_ports push_buttons[1]]
	set_property IOSTANDARD LVCMOS33 [get_ports push_buttons[1]]
set_property PACKAGE_PIN U17 [get_ports push_buttons[3]]
	set_property IOSTANDARD LVCMOS33 [get_ports push_buttons[3]]
	
	
	
	