// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="home_alarm_system_home_alarm_system,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.658500,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=41,HLS_SYN_LUT=120,HLS_VERSION=2025_1}" *)

module home_alarm_system (
        ap_clk,
        ap_rst,
        slide_switches,
        push_buttons,
        leds,
        sg_data,
        sg_enable
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input  [15:0] slide_switches;
input  [4:0] push_buttons;
output  [15:0] leds;
output  [7:0] sg_data;
output  [3:0] sg_enable;

reg[7:0] sg_data;
reg[3:0] sg_enable;

reg   [4:0] push_buttons_read_reg_241;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] slide_switches_read_reg_250;
wire   [0:0] icmp_ln53_fu_149_p2;
reg   [0:0] icmp_ln53_reg_259;
wire   [0:0] icmp_ln57_fu_155_p2;
reg   [0:0] icmp_ln57_reg_263;
wire   [0:0] icmp_ln57_1_fu_161_p2;
reg   [0:0] icmp_ln57_1_reg_267;
wire   [0:0] or_ln57_fu_167_p2;
reg   [0:0] or_ln57_reg_271;
wire   [0:0] icmp_ln108_fu_173_p2;
reg   [0:0] icmp_ln108_reg_275;
wire   [0:0] trunc_ln47_fu_179_p1;
reg   [0:0] trunc_ln47_reg_279;
wire    ap_CS_fsm_state2;
wire   [0:0] trunc_ln47_1_fu_182_p1;
reg   [0:0] trunc_ln47_1_reg_283;
reg   [0:0] tmp_reg_287;
reg   [0:0] tmp_1_reg_291;
reg   [0:0] tmp_2_reg_295;
reg   [0:0] tmp_3_reg_299;
reg   [0:0] tmp_4_reg_303;
wire    ap_CS_fsm_state4;
reg   [0:0] tmp_5_reg_307;
reg   [0:0] tmp_6_reg_311;
reg   [0:0] tmp_7_reg_315;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire   [3:0] switch_code_fu_141_p3;
wire   [2:0] window_sensors_fu_129_p1;
wire   [1:0] motion_detectors_fu_133_p3;
reg   [4:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln108_reg_275 <= icmp_ln108_fu_173_p2;
        icmp_ln53_reg_259 <= icmp_ln53_fu_149_p2;
        icmp_ln57_1_reg_267 <= icmp_ln57_1_fu_161_p2;
        icmp_ln57_reg_263 <= icmp_ln57_fu_155_p2;
        or_ln57_reg_271 <= or_ln57_fu_167_p2;
        push_buttons_read_reg_241 <= push_buttons;
        slide_switches_read_reg_250 <= slide_switches;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_1_reg_291 <= slide_switches_read_reg_250[32'd1];
        tmp_2_reg_295 <= push_buttons_read_reg_241[32'd2];
        tmp_3_reg_299 <= slide_switches_read_reg_250[32'd2];
        tmp_reg_287 <= push_buttons_read_reg_241[32'd1];
        trunc_ln47_1_reg_283 <= trunc_ln47_1_fu_182_p1;
        trunc_ln47_reg_279 <= trunc_ln47_fu_179_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_4_reg_303 <= push_buttons_read_reg_241[32'd3];
        tmp_5_reg_307 <= slide_switches_read_reg_250[32'd6];
        tmp_6_reg_311 <= push_buttons_read_reg_241[32'd4];
        tmp_7_reg_315 <= slide_switches_read_reg_250[32'd7];
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((((tmp_5_reg_307 == 1'd1) & (tmp_4_reg_303 == 1'd1) & (icmp_ln108_reg_275 == 1'd0) & (or_ln57_reg_271 == 1'd1) & (icmp_ln57_1_reg_267 == 1'd1) & (icmp_ln53_reg_259 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln47_1_reg_283 == 1'd1) & (trunc_ln47_reg_279 == 1'd1) & (icmp_ln57_reg_263 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        sg_data = 8'd249;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((tmp_1_reg_291 == 1'd1) & (tmp_reg_287 == 1'd1) & (trunc_ln47_1_reg_283 == 1'd0) & (icmp_ln57_reg_263 == 1'd1)) | ((tmp_1_reg_291 == 1'd1) & (tmp_reg_287 == 1'd1) & (trunc_ln47_reg_279 == 1'd0) & (icmp_ln57_reg_263 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_7_reg_315 == 1'd1) & (tmp_6_reg_311 == 1'd1) & (tmp_4_reg_303 == 1'd0) & (icmp_ln108_reg_275 == 1'd0) & (or_ln57_reg_271 == 1'd1) & (icmp_ln57_1_reg_267 == 1'd1) & (icmp_ln53_reg_259 == 1'd1)) | ((tmp_7_reg_315 == 1'd1) & (tmp_6_reg_311 == 1'd1) & (tmp_5_reg_307 == 1'd0) & (icmp_ln108_reg_275 == 1'd0) & (or_ln57_reg_271 == 1'd1) & (icmp_ln57_1_reg_267 == 1'd1) & (icmp_ln53_reg_259 == 1'd1)))))) begin
        sg_data = 8'd164;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_reg_287 == 1'd0) & (trunc_ln47_1_reg_283 == 1'd0) & (icmp_ln57_reg_263 == 1'd1)) | ((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_1_reg_291 == 1'd0) & (trunc_ln47_1_reg_283 == 1'd0) & (icmp_ln57_reg_263 == 1'd1))) | ((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_1_reg_291 == 1'd0) & (trunc_ln47_reg_279 == 1'd0) & (icmp_ln57_reg_263 == 1'd1))) | ((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_reg_287 == 1'd0) & (trunc_ln47_reg_279 == 1'd0) & (icmp_ln57_reg_263 == 1'd1))))) begin
        sg_data = 8'd176;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((or_ln57_fu_167_p2 == 1'd1) & (icmp_ln53_fu_149_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sg_data = 8'd134;
    end else if (((or_ln57_fu_167_p2 == 1'd0) & (icmp_ln53_fu_149_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sg_data = 8'd136;
    end else if (((icmp_ln53_fu_149_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        sg_data = 8'd192;
    end else begin
        sg_data = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_307 == 1'd1) & (tmp_4_reg_303 == 1'd1) & (icmp_ln108_reg_275 == 1'd0) & (or_ln57_reg_271 == 1'd1) & (icmp_ln57_1_reg_267 == 1'd1) & (icmp_ln53_reg_259 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_7_reg_315 == 1'd1) & (tmp_6_reg_311 == 1'd1) & (tmp_4_reg_303 == 1'd0) & (icmp_ln108_reg_275 == 1'd0) & (or_ln57_reg_271 == 1'd1) & (icmp_ln57_1_reg_267 == 1'd1) & (icmp_ln53_reg_259 == 1'd1)) | ((tmp_7_reg_315 == 1'd1) & (tmp_6_reg_311 == 1'd1) & (tmp_5_reg_307 == 1'd0) & (icmp_ln108_reg_275 == 1'd0) & (or_ln57_reg_271 == 1'd1) & (icmp_ln57_1_reg_267 == 1'd1) & (icmp_ln53_reg_259 == 1'd1)))))) begin
        sg_enable = 4'd13;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((tmp_1_reg_291 == 1'd1) & (tmp_reg_287 == 1'd1) & (trunc_ln47_1_reg_283 == 1'd0) & (icmp_ln57_reg_263 == 1'd1)) | ((tmp_1_reg_291 == 1'd1) & (tmp_reg_287 == 1'd1) & (trunc_ln47_reg_279 == 1'd0) & (icmp_ln57_reg_263 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state3) & (((((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_reg_287 == 1'd0) & (trunc_ln47_1_reg_283 == 1'd0) & (icmp_ln57_reg_263 == 1'd1)) | ((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_1_reg_291 == 1'd0) & (trunc_ln47_1_reg_283 == 1'd0) & (icmp_ln57_reg_263 == 1'd1))) | ((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_1_reg_291 == 1'd0) & (trunc_ln47_reg_279 == 1'd0) & (icmp_ln57_reg_263 == 1'd1))) | ((tmp_3_reg_299 == 1'd1) & (tmp_2_reg_295 == 1'd1) & (tmp_reg_287 == 1'd0) & (trunc_ln47_reg_279 == 1'd0) & (icmp_ln57_reg_263 == 1'd1)))) | ((trunc_ln47_1_reg_283 == 1'd1) & (trunc_ln47_reg_279 == 1'd1) & (icmp_ln57_reg_263 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        sg_enable = 4'd14;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((or_ln57_fu_167_p2 == 1'd1) & (icmp_ln53_fu_149_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((or_ln57_fu_167_p2 == 1'd0) & (icmp_ln53_fu_149_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln53_fu_149_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        sg_enable = 4'd0;
    end else begin
        sg_enable = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln108_fu_173_p2 == 1'd0) & (or_ln57_fu_167_p2 == 1'd1) & (icmp_ln57_fu_155_p2 == 1'd0) & (icmp_ln53_fu_149_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((icmp_ln108_fu_173_p2 == 1'd0) & (or_ln57_fu_167_p2 == 1'd1) & (icmp_ln57_fu_155_p2 == 1'd1) & (icmp_ln53_fu_149_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln57_1_reg_267 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign icmp_ln108_fu_173_p2 = ((push_buttons == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_149_p2 = ((switch_code_fu_141_p3 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln57_1_fu_161_p2 = ((motion_detectors_fu_133_p3 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_155_p2 = ((window_sensors_fu_129_p1 != 3'd0) ? 1'b1 : 1'b0);

assign leds = slide_switches;

assign motion_detectors_fu_133_p3 = {{slide_switches[7:6]}};

assign or_ln57_fu_167_p2 = (icmp_ln57_fu_155_p2 | icmp_ln57_1_fu_161_p2);

assign switch_code_fu_141_p3 = {{slide_switches[15:12]}};

assign trunc_ln47_1_fu_182_p1 = slide_switches_read_reg_250[0:0];

assign trunc_ln47_fu_179_p1 = push_buttons_read_reg_241[0:0];

assign window_sensors_fu_129_p1 = slide_switches[2:0];

endmodule //home_alarm_system
