
## Switches (input part)
set_property PACKAGE_PIN V17 [get_ports {digit[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[0]}]
set_property PACKAGE_PIN V16 [get_ports {digit[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[1]}]
set_property PACKAGE_PIN W16 [get_ports {digit[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[2]}]
set_property PACKAGE_PIN W17 [get_ports {digit[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[3]}]
set_property PACKAGE_PIN W15 [get_ports {digit[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[4]}]
set_property PACKAGE_PIN V15 [get_ports {digit[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[5]}]
set_property PACKAGE_PIN W14 [get_ports {digit[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[6]}]
set_property PACKAGE_PIN W13 [get_ports {digit[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[7]}]
	
	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {code7segment[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {code7segment[0]}]
set_property PACKAGE_PIN W6 [get_ports {code7segment[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {code7segment[1]}]
set_property PACKAGE_PIN U8 [get_ports {code7segment[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {code7segment[2]}]
set_property PACKAGE_PIN V8 [get_ports {code7segment[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {code7segment[3]}]
set_property PACKAGE_PIN U5 [get_ports {code7segment[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {code7segment[4]}]
set_property PACKAGE_PIN V5 [get_ports {code7segment[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {code7segment[5]}]
set_property PACKAGE_PIN U7 [get_ports {code7segment[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {code7segment[6]}]

set_property PACKAGE_PIN V7 [get_ports code7segment[7]]							
	set_property IOSTANDARD LVCMOS33 [get_ports code7segment[7]]

set_property PACKAGE_PIN U2 [get_ports {control_signals[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {control_signals[0]}]
set_property PACKAGE_PIN U4 [get_ports {control_signals[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {control_signals[1]}]
set_property PACKAGE_PIN V4 [get_ports {control_signals[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {control_signals[2]}]
set_property PACKAGE_PIN W4 [get_ports {control_signals[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {control_signals[3]}]