# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_controller.xdc

# Block Designs: bd/LED_Controller/LED_Controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_Controller || ORIG_REF_NAME==LED_Controller} -quiet] -quiet

# IP: bd/LED_Controller/ip/LED_Controller_led_ON_0_0/LED_Controller_led_ON_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_Controller_led_ON_0_0 || ORIG_REF_NAME==LED_Controller_led_ON_0_0} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/LED_Controller_Vivado/LED_Controller_Vivado.gen/sources_1/bd/LED_Controller/LED_Controller_ooc.xdc
