# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lenovo/Simulation_Linux/HLS/Seven_Seg_Single_Digit_Vivado/Seven_Seg_Single_Digit_Vivado.srcs/sources_1/bd/SevenSeg_SingleDigit/ip/SevenSeg_SingleDigit_single_seven_segment_0_0/SevenSeg_SingleDigit_single_seven_segment_0_0.xci
# IP: The module: 'SevenSeg_SingleDigit_single_seven_segment_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Seven_Seg_Single_Digit_Vivado/Seven_Seg_Single_Digit_Vivado.gen/sources_1/bd/SevenSeg_SingleDigit/ip/SevenSeg_SingleDigit_single_seven_segment_0_0/constraints/single_seven_segment_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SevenSeg_SingleDigit_single_seven_segment_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lenovo/Simulation_Linux/HLS/Seven_Seg_Single_Digit_Vivado/Seven_Seg_Single_Digit_Vivado.srcs/sources_1/bd/SevenSeg_SingleDigit/ip/SevenSeg_SingleDigit_single_seven_segment_0_0/SevenSeg_SingleDigit_single_seven_segment_0_0.xci
# IP: The module: 'SevenSeg_SingleDigit_single_seven_segment_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Seven_Seg_Single_Digit_Vivado/Seven_Seg_Single_Digit_Vivado.gen/sources_1/bd/SevenSeg_SingleDigit/ip/SevenSeg_SingleDigit_single_seven_segment_0_0/constraints/single_seven_segment_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SevenSeg_SingleDigit_single_seven_segment_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
