// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="leading_one_leading_one,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.694571,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=77,HLS_VERSION=2025_1}" *)

module leading_one (
        a,
        ap_return,
        ap_rst
);


input  [8:0] a;
output  [4:0] ap_return;
input   ap_rst;

wire   [0:0] trunc_ln41_fu_156_p1;
wire   [0:0] index_fu_160_p2;
wire   [0:0] tmp_fu_92_p3;
wire   [0:0] tmp_1_fu_100_p3;
wire   [0:0] xor_ln17_fu_174_p2;
wire   [0:0] or_ln20_fu_186_p2;
wire   [0:0] tmp_2_fu_108_p3;
wire   [0:0] xor_ln20_fu_192_p2;
wire   [0:0] or_ln23_fu_204_p2;
wire   [0:0] tmp_3_fu_116_p3;
wire   [0:0] xor_ln23_fu_210_p2;
wire   [0:0] or_ln26_fu_222_p2;
wire   [0:0] tmp_4_fu_124_p3;
wire   [0:0] xor_ln26_fu_228_p2;
wire   [0:0] or_ln29_fu_240_p2;
wire   [0:0] tmp_5_fu_132_p3;
wire   [0:0] xor_ln29_fu_246_p2;
wire   [0:0] or_ln32_fu_258_p2;
wire   [0:0] tmp_6_fu_140_p3;
wire   [0:0] xor_ln32_fu_264_p2;
wire   [0:0] or_ln35_fu_276_p2;
wire   [0:0] tmp_7_fu_148_p3;
wire   [0:0] xor_ln35_fu_282_p2;
wire   [0:0] and_ln20_fu_180_p2;
wire   [0:0] and_ln23_fu_198_p2;
wire   [0:0] and_ln26_fu_216_p2;
wire   [0:0] and_ln29_fu_234_p2;
wire   [0:0] and_ln32_fu_252_p2;
wire   [0:0] and_ln35_fu_270_p2;
wire   [0:0] and_ln38_fu_288_p2;
wire   [4:0] retval_8_fu_314_p18;
wire   [4:0] retval_8_fu_314_p19;
wire   [7:0] retval_8_fu_314_p20;
wire   [4:0] retval_8_fu_314_p21;
wire  signed [7:0] retval_8_fu_314_p1;
wire   [7:0] retval_8_fu_314_p3;
wire   [7:0] retval_8_fu_314_p5;
wire   [7:0] retval_8_fu_314_p7;
wire   [7:0] retval_8_fu_314_p9;
wire   [7:0] retval_8_fu_314_p11;
wire   [7:0] retval_8_fu_314_p13;
wire   [7:0] retval_8_fu_314_p15;
wire   [7:0] retval_8_fu_314_p17;

(* dissolve_hierarchy = "yes" *) leading_one_sparsemux_19_8_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h80 ),
    .din0_WIDTH( 5 ),
    .CASE1( 8'h40 ),
    .din1_WIDTH( 5 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 5 ),
    .CASE3( 8'h10 ),
    .din3_WIDTH( 5 ),
    .CASE4( 8'h8 ),
    .din4_WIDTH( 5 ),
    .CASE5( 8'h4 ),
    .din5_WIDTH( 5 ),
    .CASE6( 8'h2 ),
    .din6_WIDTH( 5 ),
    .CASE7( 8'h1 ),
    .din7_WIDTH( 5 ),
    .CASE8( 8'h0 ),
    .din8_WIDTH( 5 ),
    .def_WIDTH( 5 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 5 ))
sparsemux_19_8_5_1_1_U1(
    .din0(5'd8),
    .din1(5'd7),
    .din2(5'd6),
    .din3(5'd5),
    .din4(5'd4),
    .din5(5'd3),
    .din6(5'd2),
    .din7(5'd1),
    .din8(retval_8_fu_314_p18),
    .def(retval_8_fu_314_p19),
    .sel(retval_8_fu_314_p20),
    .dout(retval_8_fu_314_p21)
);

assign and_ln20_fu_180_p2 = (xor_ln17_fu_174_p2 & tmp_1_fu_100_p3);

assign and_ln23_fu_198_p2 = (xor_ln20_fu_192_p2 & tmp_2_fu_108_p3);

assign and_ln26_fu_216_p2 = (xor_ln23_fu_210_p2 & tmp_3_fu_116_p3);

assign and_ln29_fu_234_p2 = (xor_ln26_fu_228_p2 & tmp_4_fu_124_p3);

assign and_ln32_fu_252_p2 = (xor_ln29_fu_246_p2 & tmp_5_fu_132_p3);

assign and_ln35_fu_270_p2 = (xor_ln32_fu_264_p2 & tmp_6_fu_140_p3);

assign and_ln38_fu_288_p2 = (xor_ln35_fu_282_p2 & tmp_7_fu_148_p3);

assign index_fu_160_p2 = (trunc_ln41_fu_156_p1 ^ 1'd1);

assign or_ln20_fu_186_p2 = (tmp_fu_92_p3 | tmp_1_fu_100_p3);

assign or_ln23_fu_204_p2 = (tmp_2_fu_108_p3 | or_ln20_fu_186_p2);

assign or_ln26_fu_222_p2 = (tmp_3_fu_116_p3 | or_ln23_fu_204_p2);

assign or_ln29_fu_240_p2 = (tmp_4_fu_124_p3 | or_ln26_fu_222_p2);

assign or_ln32_fu_258_p2 = (tmp_5_fu_132_p3 | or_ln29_fu_240_p2);

assign or_ln35_fu_276_p2 = (tmp_6_fu_140_p3 | or_ln32_fu_258_p2);

assign tmp_1_fu_100_p3 = a[32'd7];

assign tmp_2_fu_108_p3 = a[32'd6];

assign tmp_3_fu_116_p3 = a[32'd5];

assign tmp_4_fu_124_p3 = a[32'd4];

assign tmp_5_fu_132_p3 = a[32'd3];

assign tmp_6_fu_140_p3 = a[32'd2];

assign tmp_7_fu_148_p3 = a[32'd1];

assign tmp_fu_92_p3 = a[32'd8];

assign trunc_ln41_fu_156_p1 = a[0:0];

assign xor_ln17_fu_174_p2 = (tmp_fu_92_p3 ^ 1'd1);

assign xor_ln20_fu_192_p2 = (or_ln20_fu_186_p2 ^ 1'd1);

assign xor_ln23_fu_210_p2 = (or_ln23_fu_204_p2 ^ 1'd1);

assign xor_ln26_fu_228_p2 = (or_ln26_fu_222_p2 ^ 1'd1);

assign xor_ln29_fu_246_p2 = (or_ln29_fu_240_p2 ^ 1'd1);

assign xor_ln32_fu_264_p2 = (or_ln32_fu_258_p2 ^ 1'd1);

assign xor_ln35_fu_282_p2 = (or_ln35_fu_276_p2 ^ 1'd1);

assign ap_return = retval_8_fu_314_p21;

assign retval_8_fu_314_p18 = ((index_fu_160_p2[0:0] == 1'b1) ? 5'd31 : 5'd0);

assign retval_8_fu_314_p19 = 'bx;

assign retval_8_fu_314_p20 = {{{{{{{{tmp_fu_92_p3}, {and_ln20_fu_180_p2}}, {and_ln23_fu_198_p2}}, {and_ln26_fu_216_p2}}, {and_ln29_fu_234_p2}}, {and_ln32_fu_252_p2}}, {and_ln35_fu_270_p2}}, {and_ln38_fu_288_p2}};

endmodule //leading_one
