// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dummy_comb_circuit_dummy_comb_circuit,hls_ip_2025_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.978000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=6,HLS_VERSION=2025_1}" *)

module dummy_comb_circuit (
        a,
        b,
        c,
        d,
        ap_rst
);


input  [0:0] a;
input  [0:0] b;
input  [0:0] c;
output  [0:0] d;
input   ap_rst;

wire   [0:0] and_ln14_fu_57_p2;
wire   [0:0] xor_ln14_fu_63_p2;

assign and_ln14_fu_57_p2 = (b & a);

assign xor_ln14_fu_63_p2 = (c ^ 1'd1);

assign d = (xor_ln14_fu_63_p2 | and_ln14_fu_57_p2);

endmodule //dummy_comb_circuit
