-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity home_alarm_system is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    slide_switches : IN STD_LOGIC_VECTOR (15 downto 0);
    push_buttons : IN STD_LOGIC_VECTOR (4 downto 0);
    leds : OUT STD_LOGIC_VECTOR (15 downto 0);
    sg_data : OUT STD_LOGIC_VECTOR (7 downto 0);
    sg_enable : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of home_alarm_system is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "home_alarm_system_home_alarm_system,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.658500,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=41,HLS_SYN_LUT=120,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_C0 : STD_LOGIC_VECTOR (7 downto 0) := "11000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_88 : STD_LOGIC_VECTOR (7 downto 0) := "10001000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_86 : STD_LOGIC_VECTOR (7 downto 0) := "10000110";
    constant ap_const_lv8_B0 : STD_LOGIC_VECTOR (7 downto 0) := "10110000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_A4 : STD_LOGIC_VECTOR (7 downto 0) := "10100100";
    constant ap_const_lv8_F9 : STD_LOGIC_VECTOR (7 downto 0) := "11111001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

    signal push_buttons_read_reg_241 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal slide_switches_read_reg_250 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln53_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_259 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_263 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_1_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_1_reg_267 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln57_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln57_reg_271 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_reg_275 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln47_fu_179_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln47_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln47_1_fu_182_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln47_1_reg_283 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_291 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_295 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_299 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_303 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_5_reg_307 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_311 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_315 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal switch_code_fu_141_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal window_sensors_fu_129_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal motion_detectors_fu_133_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln108_reg_275 <= icmp_ln108_fu_173_p2;
                icmp_ln53_reg_259 <= icmp_ln53_fu_149_p2;
                icmp_ln57_1_reg_267 <= icmp_ln57_1_fu_161_p2;
                icmp_ln57_reg_263 <= icmp_ln57_fu_155_p2;
                or_ln57_reg_271 <= or_ln57_fu_167_p2;
                push_buttons_read_reg_241 <= push_buttons;
                slide_switches_read_reg_250 <= slide_switches;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_1_reg_291 <= slide_switches_read_reg_250(1 downto 1);
                tmp_2_reg_295 <= push_buttons_read_reg_241(2 downto 2);
                tmp_3_reg_299 <= slide_switches_read_reg_250(2 downto 2);
                tmp_reg_287 <= push_buttons_read_reg_241(1 downto 1);
                trunc_ln47_1_reg_283 <= trunc_ln47_1_fu_182_p1;
                trunc_ln47_reg_279 <= trunc_ln47_fu_179_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_4_reg_303 <= push_buttons_read_reg_241(3 downto 3);
                tmp_5_reg_307 <= slide_switches_read_reg_250(6 downto 6);
                tmp_6_reg_311 <= push_buttons_read_reg_241(4 downto 4);
                tmp_7_reg_315 <= slide_switches_read_reg_250(7 downto 7);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln53_fu_149_p2, icmp_ln57_fu_155_p2, icmp_ln57_1_reg_267, or_ln57_fu_167_p2, icmp_ln108_fu_173_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln108_fu_173_p2 = ap_const_lv1_0) and (or_ln57_fu_167_p2 = ap_const_lv1_1) and (icmp_ln57_fu_155_p2 = ap_const_lv1_0) and (icmp_ln53_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((icmp_ln108_fu_173_p2 = ap_const_lv1_0) and (or_ln57_fu_167_p2 = ap_const_lv1_1) and (icmp_ln57_fu_155_p2 = ap_const_lv1_1) and (icmp_ln53_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln57_1_reg_267 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    icmp_ln108_fu_173_p2 <= "1" when (push_buttons = ap_const_lv5_0) else "0";
    icmp_ln53_fu_149_p2 <= "1" when (switch_code_fu_141_p3 = ap_const_lv4_B) else "0";
    icmp_ln57_1_fu_161_p2 <= "0" when (motion_detectors_fu_133_p3 = ap_const_lv2_0) else "1";
    icmp_ln57_fu_155_p2 <= "0" when (window_sensors_fu_129_p1 = ap_const_lv3_0) else "1";
    leds <= slide_switches;
    motion_detectors_fu_133_p3 <= slide_switches(7 downto 6);
    or_ln57_fu_167_p2 <= (icmp_ln57_fu_155_p2 or icmp_ln57_1_fu_161_p2);

    sg_data_assign_proc : process(ap_CS_fsm_state1, icmp_ln53_fu_149_p2, icmp_ln53_reg_259, icmp_ln57_reg_263, icmp_ln57_1_reg_267, or_ln57_fu_167_p2, or_ln57_reg_271, icmp_ln108_reg_275, trunc_ln47_reg_279, ap_CS_fsm_state2, trunc_ln47_1_reg_283, tmp_reg_287, tmp_1_reg_291, tmp_2_reg_295, tmp_3_reg_299, tmp_4_reg_303, ap_CS_fsm_state4, tmp_5_reg_307, tmp_6_reg_311, tmp_7_reg_315, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((((tmp_5_reg_307 = ap_const_lv1_1) and (tmp_4_reg_303 = ap_const_lv1_1) and (icmp_ln108_reg_275 = ap_const_lv1_0) and (or_ln57_reg_271 = ap_const_lv1_1) and (icmp_ln57_1_reg_267 = ap_const_lv1_1) and (icmp_ln53_reg_259 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((trunc_ln47_1_reg_283 = ap_const_lv1_1) and (trunc_ln47_reg_279 = ap_const_lv1_1) and (icmp_ln57_reg_263 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            sg_data <= ap_const_lv8_F9;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (((tmp_1_reg_291 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_1) and (trunc_ln47_1_reg_283 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1)) or ((tmp_1_reg_291 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_1) and (trunc_ln47_reg_279 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (((tmp_7_reg_315 = ap_const_lv1_1) and (tmp_6_reg_311 = ap_const_lv1_1) and (tmp_4_reg_303 = ap_const_lv1_0) and (icmp_ln108_reg_275 = ap_const_lv1_0) and (or_ln57_reg_271 = ap_const_lv1_1) and (icmp_ln57_1_reg_267 = ap_const_lv1_1) and (icmp_ln53_reg_259 = ap_const_lv1_1)) or ((tmp_7_reg_315 = ap_const_lv1_1) and (tmp_6_reg_311 = ap_const_lv1_1) and (tmp_5_reg_307 = ap_const_lv1_0) and (icmp_ln108_reg_275 = ap_const_lv1_0) and (or_ln57_reg_271 = ap_const_lv1_1) and (icmp_ln57_1_reg_267 = ap_const_lv1_1) and (icmp_ln53_reg_259 = ap_const_lv1_1)))))) then 
            sg_data <= ap_const_lv8_A4;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (((((tmp_3_reg_299 = ap_const_lv1_1) and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_0) and (trunc_ln47_1_reg_283 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1)) or ((tmp_3_reg_299 = ap_const_lv1_1) and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_1_reg_291 = ap_const_lv1_0) and (trunc_ln47_1_reg_283 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1))) or ((tmp_3_reg_299 = ap_const_lv1_1) and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_1_reg_291 = ap_const_lv1_0) and (trunc_ln47_reg_279 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1))) or ((tmp_3_reg_299 = ap_const_lv1_1) and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_0) and (trunc_ln47_reg_279 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1))))) then 
            sg_data <= ap_const_lv8_B0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((or_ln57_fu_167_p2 = ap_const_lv1_1) and (icmp_ln53_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            sg_data <= ap_const_lv8_86;
        elsif (((or_ln57_fu_167_p2 = ap_const_lv1_0) and (icmp_ln53_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            sg_data <= ap_const_lv8_88;
        elsif (((icmp_ln53_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            sg_data <= ap_const_lv8_C0;
        else 
            sg_data <= "XXXXXXXX";
        end if; 
    end process;


    sg_enable_assign_proc : process(ap_CS_fsm_state1, icmp_ln53_fu_149_p2, icmp_ln53_reg_259, icmp_ln57_reg_263, icmp_ln57_1_reg_267, or_ln57_fu_167_p2, or_ln57_reg_271, icmp_ln108_reg_275, trunc_ln47_reg_279, ap_CS_fsm_state2, trunc_ln47_1_reg_283, tmp_reg_287, tmp_1_reg_291, tmp_2_reg_295, tmp_3_reg_299, tmp_4_reg_303, ap_CS_fsm_state4, tmp_5_reg_307, tmp_6_reg_311, tmp_7_reg_315, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((((tmp_5_reg_307 = ap_const_lv1_1) and (tmp_4_reg_303 = ap_const_lv1_1) and (icmp_ln108_reg_275 = ap_const_lv1_0) and (or_ln57_reg_271 = ap_const_lv1_1) and (icmp_ln57_1_reg_267 = ap_const_lv1_1) and (icmp_ln53_reg_259 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (((tmp_7_reg_315 = ap_const_lv1_1) and (tmp_6_reg_311 = ap_const_lv1_1) and (tmp_4_reg_303 = ap_const_lv1_0) and (icmp_ln108_reg_275 = ap_const_lv1_0) and (or_ln57_reg_271 = ap_const_lv1_1) and (icmp_ln57_1_reg_267 = ap_const_lv1_1) and (icmp_ln53_reg_259 = ap_const_lv1_1)) or ((tmp_7_reg_315 = ap_const_lv1_1) and (tmp_6_reg_311 = ap_const_lv1_1) and (tmp_5_reg_307 = ap_const_lv1_0) and (icmp_ln108_reg_275 = ap_const_lv1_0) and (or_ln57_reg_271 = ap_const_lv1_1) and (icmp_ln57_1_reg_267 = ap_const_lv1_1) and (icmp_ln53_reg_259 = ap_const_lv1_1)))))) then 
            sg_enable <= ap_const_lv4_D;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (((tmp_1_reg_291 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_1) and (trunc_ln47_1_reg_283 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1)) or ((tmp_1_reg_291 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_1) and (trunc_ln47_reg_279 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (((((tmp_3_reg_299 = ap_const_lv1_1) and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_0) and (trunc_ln47_1_reg_283 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1)) or ((tmp_3_reg_299 = ap_const_lv1_1) and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_1_reg_291 = ap_const_lv1_0) and (trunc_ln47_1_reg_283 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1))) or ((tmp_3_reg_299 = ap_const_lv1_1) and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_1_reg_291 = ap_const_lv1_0) and (trunc_ln47_reg_279 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1))) or ((tmp_3_reg_299 = ap_const_lv1_1) 
    and (tmp_2_reg_295 = ap_const_lv1_1) and (tmp_reg_287 = ap_const_lv1_0) and (trunc_ln47_reg_279 = ap_const_lv1_0) and (icmp_ln57_reg_263 = ap_const_lv1_1)))) or ((trunc_ln47_1_reg_283 = ap_const_lv1_1) and (trunc_ln47_reg_279 = ap_const_lv1_1) and (icmp_ln57_reg_263 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            sg_enable <= ap_const_lv4_E;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((or_ln57_fu_167_p2 = ap_const_lv1_1) and (icmp_ln53_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((or_ln57_fu_167_p2 = ap_const_lv1_0) and (icmp_ln53_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln53_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            sg_enable <= ap_const_lv4_0;
        else 
            sg_enable <= "XXXX";
        end if; 
    end process;

    switch_code_fu_141_p3 <= slide_switches(15 downto 12);
    trunc_ln47_1_fu_182_p1 <= slide_switches_read_reg_250(1 - 1 downto 0);
    trunc_ln47_fu_179_p1 <= push_buttons_read_reg_241(1 - 1 downto 0);
    window_sensors_fu_129_p1 <= slide_switches(3 - 1 downto 0);
end behav;
