# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/seven_seg_single_digit.xdc

# Block Designs: bd/SevenSeg_SingleDigit/SevenSeg_SingleDigit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SevenSeg_SingleDigit || ORIG_REF_NAME==SevenSeg_SingleDigit} -quiet] -quiet

# IP: bd/SevenSeg_SingleDigit/ip/SevenSeg_SingleDigit_single_seven_segment_0_0/SevenSeg_SingleDigit_single_seven_segment_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SevenSeg_SingleDigit_single_seven_segment_0_0 || ORIG_REF_NAME==SevenSeg_SingleDigit_single_seven_segment_0_0} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/Seven_Seg_Single_Digit_Vivado/Seven_Seg_Single_Digit_Vivado.gen/sources_1/bd/SevenSeg_SingleDigit/SevenSeg_SingleDigit_ooc.xdc
