## Switches
set_property PACKAGE_PIN V17 [get_ports {input_nb[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[0]}]
set_property PACKAGE_PIN V16 [get_ports {input_nb[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[1]}]
set_property PACKAGE_PIN W16 [get_ports {input_nb[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[2]}]
set_property PACKAGE_PIN W17 [get_ports {input_nb[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[3]}]
set_property PACKAGE_PIN W15 [get_ports {input_nb[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[4]}]
set_property PACKAGE_PIN V15 [get_ports {input_nb[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[5]}]
set_property PACKAGE_PIN W14 [get_ports {input_nb[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[6]}]
set_property PACKAGE_PIN W13 [get_ports {input_nb[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[7]}]
set_property PACKAGE_PIN V2 [get_ports {input_nb[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input_nb[8]}]
	
## LED
set_property PACKAGE_PIN U16 [get_ports {index_lead_one[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {index_lead_one[0]}]
set_property PACKAGE_PIN E19 [get_ports {index_lead_one[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {index_lead_one[1]}]
set_property PACKAGE_PIN U19 [get_ports {index_lead_one[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {index_lead_one[2]}]
set_property PACKAGE_PIN V19 [get_ports {index_lead_one[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {index_lead_one[3]}]
set_property PACKAGE_PIN W18 [get_ports {index_lead_one[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {index_lead_one[4]}]