# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lenovo/Simulation_Linux/HLS/SwitcheLed_Vivado/SwitcheLed_Vivado.srcs/sources_1/bd/switche_LED/ip/switche_LED_led_via_switche_0_0/switche_LED_led_via_switche_0_0.xci
# IP: The module: 'switche_LED_led_via_switche_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/SwitcheLed_Vivado/SwitcheLed_Vivado.gen/sources_1/bd/switche_LED/ip/switche_LED_led_via_switche_0_0/constraints/led_via_switche_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'switche_LED_led_via_switche_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lenovo/Simulation_Linux/HLS/SwitcheLed_Vivado/SwitcheLed_Vivado.srcs/sources_1/bd/switche_LED/ip/switche_LED_led_via_switche_0_0/switche_LED_led_via_switche_0_0.xci
# IP: The module: 'switche_LED_led_via_switche_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/SwitcheLed_Vivado/SwitcheLed_Vivado.gen/sources_1/bd/switche_LED/ip/switche_LED_led_via_switche_0_0/constraints/led_via_switche_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'switche_LED_led_via_switche_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
