# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/leading_one.xdc

# Block Designs: bd/leading_one/leading_one.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==leading_one || ORIG_REF_NAME==leading_one} -quiet] -quiet

# IP: bd/leading_one/ip/leading_one_leading_one_0_0/leading_one_leading_one_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==leading_one_leading_one_0_0 || ORIG_REF_NAME==leading_one_leading_one_0_0} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/Leading_One_Vivado/Leading_One_Vivado.gen/sources_1/bd/leading_one/leading_one_ooc.xdc
