# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dummy_comb_cicrcuit.xdc

# Block Designs: bd/Comb_circuit/Comb_circuit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Comb_circuit || ORIG_REF_NAME==Comb_circuit} -quiet] -quiet

# IP: bd/Comb_circuit/ip/Comb_circuit_dummy_comb_circuit_0_0/Comb_circuit_dummy_comb_circuit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Comb_circuit_dummy_comb_circuit_0_0 || ORIG_REF_NAME==Comb_circuit_dummy_comb_circuit_0_0} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/Dummy_Comb_Circuit/Dummy_Comb_Circuit.gen/sources_1/bd/Comb_circuit/Comb_circuit_ooc.xdc
