# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lenovo/Simulation_Linux/HLS/Comb_Lock_Vivado/Comb_Lock_Vivado.srcs/sources_1/bd/comb_lock/ip/comb_lock_pulse_generator_1_1/comb_lock_pulse_generator_1_1.xci
# IP: The module: 'comb_lock_pulse_generator_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Comb_Lock_Vivado/Comb_Lock_Vivado.gen/sources_1/bd/comb_lock/ip/comb_lock_pulse_generator_1_1/constraints/pulse_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'comb_lock_pulse_generator_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lenovo/Simulation_Linux/HLS/Comb_Lock_Vivado/Comb_Lock_Vivado.srcs/sources_1/bd/comb_lock/ip/comb_lock_pulse_generator_1_1/comb_lock_pulse_generator_1_1.xci
# IP: The module: 'comb_lock_pulse_generator_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Comb_Lock_Vivado/Comb_Lock_Vivado.gen/sources_1/bd/comb_lock/ip/comb_lock_pulse_generator_1_1/constraints/pulse_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'comb_lock_pulse_generator_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
