# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/switcheLed.xdc

# Block Designs: bd/switche_LED/switche_LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==switche_LED || ORIG_REF_NAME==switche_LED} -quiet] -quiet

# IP: bd/switche_LED/ip/switche_LED_led_via_switche_0_0/switche_LED_led_via_switche_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==switche_LED_led_via_switche_0_0 || ORIG_REF_NAME==switche_LED_led_via_switche_0_0} -quiet] -quiet

# XDC: /home/lenovo/Simulation_Linux/HLS/SwitcheLed_Vivado/SwitcheLed_Vivado.gen/sources_1/bd/switche_LED/switche_LED_ooc.xdc
