# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lenovo/Simulation_Linux/HLS/Dummy_Comb_Circuit/Dummy_Comb_Circuit.srcs/sources_1/bd/Comb_circuit/ip/Comb_circuit_dummy_comb_circuit_0_0/Comb_circuit_dummy_comb_circuit_0_0.xci
# IP: The module: 'Comb_circuit_dummy_comb_circuit_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Dummy_Comb_Circuit/Dummy_Comb_Circuit.gen/sources_1/bd/Comb_circuit/ip/Comb_circuit_dummy_comb_circuit_0_0/constraints/dummy_comb_circuit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Comb_circuit_dummy_comb_circuit_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lenovo/Simulation_Linux/HLS/Dummy_Comb_Circuit/Dummy_Comb_Circuit.srcs/sources_1/bd/Comb_circuit/ip/Comb_circuit_dummy_comb_circuit_0_0/Comb_circuit_dummy_comb_circuit_0_0.xci
# IP: The module: 'Comb_circuit_dummy_comb_circuit_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Dummy_Comb_Circuit/Dummy_Comb_Circuit.gen/sources_1/bd/Comb_circuit/ip/Comb_circuit_dummy_comb_circuit_0_0/constraints/dummy_comb_circuit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Comb_circuit_dummy_comb_circuit_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
