-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity combination_lock is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (3 downto 0);
    enter : IN STD_LOGIC_VECTOR (0 downto 0);
    lock : IN STD_LOGIC_VECTOR (0 downto 0);
    door_open : OUT STD_LOGIC_VECTOR (0 downto 0);
    seven_segment_data : OUT STD_LOGIC_VECTOR (7 downto 0);
    seven_segment_enable : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of combination_lock is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "combination_lock_combination_lock,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.301286,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4,HLS_SYN_LUT=208,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv9_40 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_const_lv9_20 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_const_lv9_10 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_C0 : STD_LOGIC_VECTOR (7 downto 0) := "11000000";
    constant ap_const_lv8_F9 : STD_LOGIC_VECTOR (7 downto 0) := "11111001";
    constant ap_const_lv8_A4 : STD_LOGIC_VECTOR (7 downto 0) := "10100100";
    constant ap_const_lv8_B0 : STD_LOGIC_VECTOR (7 downto 0) := "10110000";
    constant ap_const_lv8_99 : STD_LOGIC_VECTOR (7 downto 0) := "10011001";

    signal state : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal next_state_4_fu_340_p21 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal door_open_local_2_fu_396_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_0_0_0_s_fu_423_p13 : STD_LOGIC_VECTOR (7 downto 0);
    signal next_state_1_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal next_state_2_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal door_open_local_1_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_1_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_2_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_3_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_4_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln62_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_1_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_2_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_3_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_4_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_5_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_6_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_7_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal next_state_4_fu_340_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal next_state_4_fu_340_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal next_state_4_fu_340_p6 : STD_LOGIC_VECTOR (2 downto 0);
    signal next_state_4_fu_340_p8 : STD_LOGIC_VECTOR (2 downto 0);
    signal next_state_4_fu_340_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal next_state_4_fu_340_p19 : STD_LOGIC_VECTOR (2 downto 0);
    signal next_state_4_fu_340_p20 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp_fu_318_p10 : STD_LOGIC_VECTOR (8 downto 0);
    signal door_open_local_2_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal door_open_local_2_fu_396_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal door_open_local_2_fu_396_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_0_0_0_s_fu_423_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal next_state_4_fu_340_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p5 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p7 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p9 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p11 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p13 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p15 : STD_LOGIC_VECTOR (8 downto 0);
    signal next_state_4_fu_340_p17 : STD_LOGIC_VECTOR (8 downto 0);
    signal door_open_local_2_fu_396_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal door_open_local_2_fu_396_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal door_open_local_2_fu_396_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_0_0_0_s_fu_423_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_0_0_0_s_fu_423_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_0_0_0_s_fu_423_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_0_0_0_s_fu_423_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp_0_0_0_s_fu_423_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component combination_lock_sparsemux_19_9_3_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (8 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (8 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (8 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (8 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (8 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (8 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (8 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (8 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (8 downto 0);
        din8_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (2 downto 0);
        din3 : IN STD_LOGIC_VECTOR (2 downto 0);
        din4 : IN STD_LOGIC_VECTOR (2 downto 0);
        din5 : IN STD_LOGIC_VECTOR (2 downto 0);
        din6 : IN STD_LOGIC_VECTOR (2 downto 0);
        din7 : IN STD_LOGIC_VECTOR (2 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        def : IN STD_LOGIC_VECTOR (2 downto 0);
        sel : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component combination_lock_sparsemux_7_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component combination_lock_sparsemux_11_32_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (31 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (31 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (31 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (31 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (31 downto 0);
        din4_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    sparsemux_19_9_3_1_1_U1 : component combination_lock_sparsemux_19_9_3_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100000000",
        din0_WIDTH => 3,
        CASE1 => "010000000",
        din1_WIDTH => 3,
        CASE2 => "001000000",
        din2_WIDTH => 3,
        CASE3 => "000100000",
        din3_WIDTH => 3,
        CASE4 => "000010000",
        din4_WIDTH => 3,
        CASE5 => "000001000",
        din5_WIDTH => 3,
        CASE6 => "000000100",
        din6_WIDTH => 3,
        CASE7 => "000000010",
        din7_WIDTH => 3,
        CASE8 => "000000001",
        din8_WIDTH => 3,
        def_WIDTH => 3,
        sel_WIDTH => 9,
        dout_WIDTH => 3)
    port map (
        din0 => next_state_4_fu_340_p2,
        din1 => next_state_4_fu_340_p4,
        din2 => next_state_4_fu_340_p6,
        din3 => next_state_4_fu_340_p8,
        din4 => next_state_4_fu_340_p10,
        din5 => ap_const_lv3_0,
        din6 => ap_const_lv3_1,
        din7 => ap_const_lv3_2,
        din8 => ap_const_lv3_3,
        def => next_state_4_fu_340_p19,
        sel => next_state_4_fu_340_p20,
        dout => next_state_4_fu_340_p21);

    sparsemux_7_2_1_1_1_U2 : component combination_lock_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => door_open_local_2_fu_396_p2,
        din1 => door_open_local_1_fu_220_p2,
        din2 => ap_const_lv1_0,
        def => door_open_local_2_fu_396_p7,
        sel => door_open_local_2_fu_396_p8,
        dout => door_open_local_2_fu_396_p9);

    sparsemux_11_32_8_1_1_U3 : component combination_lock_sparsemux_11_32_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000000000000000000000000000000",
        din0_WIDTH => 8,
        CASE1 => "00000000000000000000000000000001",
        din1_WIDTH => 8,
        CASE2 => "00000000000000000000000000000010",
        din2_WIDTH => 8,
        CASE3 => "00000000000000000000000000000011",
        din3_WIDTH => 8,
        CASE4 => "00000000000000000000000000000100",
        din4_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 32,
        dout_WIDTH => 8)
    port map (
        din0 => ap_const_lv8_C0,
        din1 => ap_const_lv8_F9,
        din2 => ap_const_lv8_A4,
        din3 => ap_const_lv8_B0,
        din4 => ap_const_lv8_99,
        def => ap_const_lv8_C0,
        sel => ref_tmp_0_0_0_s_fu_423_p12,
        dout => ref_tmp_0_0_0_s_fu_423_p13);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                state <= next_state_4_fu_340_p21;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln62_1_fu_258_p2 <= (icmp_ln95_2_fu_252_p2 and enter);
    and_ln62_2_fu_270_p2 <= (icmp_ln95_3_fu_264_p2 and enter);
    and_ln62_3_fu_282_p2 <= (icmp_ln95_4_fu_276_p2 and enter);
    and_ln62_4_fu_294_p2 <= (xor_ln62_fu_288_p2 and icmp_ln95_4_fu_276_p2);
    and_ln62_5_fu_300_p2 <= (xor_ln62_fu_288_p2 and icmp_ln95_3_fu_264_p2);
    and_ln62_6_fu_306_p2 <= (xor_ln62_fu_288_p2 and icmp_ln95_2_fu_252_p2);
    and_ln62_7_fu_312_p2 <= (xor_ln62_fu_288_p2 and icmp_ln95_1_fu_240_p2);
    and_ln62_fu_246_p2 <= (icmp_ln95_1_fu_240_p2 and enter);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    door_open <= door_open_local_2_fu_396_p9;
    door_open_local_1_fu_220_p2 <= "1" when (x = ap_const_lv4_6) else "0";
    door_open_local_2_fu_396_p2 <= (lock xor ap_const_lv1_1);
    door_open_local_2_fu_396_p7 <= "X";
    door_open_local_2_fu_396_p8 <= (icmp_ln95_fu_234_p2 & and_ln62_fu_246_p2);
    icmp_ln135_fu_192_p2 <= "1" when (x = ap_const_lv4_3) else "0";
    icmp_ln95_1_fu_240_p2 <= "1" when (state = ap_const_lv3_3) else "0";
    icmp_ln95_2_fu_252_p2 <= "1" when (state = ap_const_lv3_2) else "0";
    icmp_ln95_3_fu_264_p2 <= "1" when (state = ap_const_lv3_1) else "0";
    icmp_ln95_4_fu_276_p2 <= "1" when (state = ap_const_lv3_0) else "0";
    icmp_ln95_fu_234_p2 <= "1" when (state = ap_const_lv3_4) else "0";
    next_state_1_fu_182_p2 <= "1" when (x = ap_const_lv4_2) else "0";
    next_state_2_fu_206_p2 <= "1" when (x = ap_const_lv4_4) else "0";
    next_state_4_fu_340_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(next_state_1_fu_182_p2),3));
    next_state_4_fu_340_p19 <= "XXX";
    next_state_4_fu_340_p2 <= 
        ap_const_lv3_0 when (lock(0) = '1') else 
        ap_const_lv3_4;
    next_state_4_fu_340_p20 <= ((((((((icmp_ln95_fu_234_p2 & and_ln62_fu_246_p2) & and_ln62_1_fu_258_p2) & and_ln62_2_fu_270_p2) & and_ln62_3_fu_282_p2) & and_ln62_4_fu_294_p2) & and_ln62_5_fu_300_p2) & and_ln62_6_fu_306_p2) & and_ln62_7_fu_312_p2);
    next_state_4_fu_340_p4 <= 
        ap_const_lv3_4 when (door_open_local_1_fu_220_p2(0) = '1') else 
        ap_const_lv3_0;
    next_state_4_fu_340_p6 <= 
        ap_const_lv3_3 when (next_state_2_fu_206_p2(0) = '1') else 
        ap_const_lv3_0;
    next_state_4_fu_340_p8 <= 
        ap_const_lv3_2 when (icmp_ln135_fu_192_p2(0) = '1') else 
        ap_const_lv3_0;
    ref_tmp_0_0_0_s_fu_423_p12 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(next_state_4_fu_340_p21),32));
    sel_tmp_fu_318_p10 <= ((((((((icmp_ln95_fu_234_p2 & and_ln62_fu_246_p2) & and_ln62_1_fu_258_p2) & and_ln62_2_fu_270_p2) & and_ln62_3_fu_282_p2) & and_ln62_4_fu_294_p2) & and_ln62_5_fu_300_p2) & and_ln62_6_fu_306_p2) & and_ln62_7_fu_312_p2);
    seven_segment_data <= ref_tmp_0_0_0_s_fu_423_p13;
    seven_segment_enable <= ap_const_lv4_E;
    xor_ln62_fu_288_p2 <= (enter xor ap_const_lv1_1);
end behav;
