# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lenovo/Simulation_Linux/HLS/Parallel_Serial_Sys_Vivado/Parallel_Serial_Sys_Vivado.srcs/sources_1/bd/paralle_serial_sys/ip/paralle_serial_sys_serial2parallel_0_0/paralle_serial_sys_serial2parallel_0_0.xci
# IP: The module: 'paralle_serial_sys_serial2parallel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Parallel_Serial_Sys_Vivado/Parallel_Serial_Sys_Vivado.gen/sources_1/bd/paralle_serial_sys/ip/paralle_serial_sys_serial2parallel_0_0/constraints/serial2parallel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'paralle_serial_sys_serial2parallel_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lenovo/Simulation_Linux/HLS/Parallel_Serial_Sys_Vivado/Parallel_Serial_Sys_Vivado.srcs/sources_1/bd/paralle_serial_sys/ip/paralle_serial_sys_serial2parallel_0_0/paralle_serial_sys_serial2parallel_0_0.xci
# IP: The module: 'paralle_serial_sys_serial2parallel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lenovo/Simulation_Linux/HLS/Parallel_Serial_Sys_Vivado/Parallel_Serial_Sys_Vivado.gen/sources_1/bd/paralle_serial_sys/ip/paralle_serial_sys_serial2parallel_0_0/constraints/serial2parallel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'paralle_serial_sys_serial2parallel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
